name = input('Digite seu nome')
city = input('Digite a cidade')
gender = input('Digite o sexo')
age = input('Digite a idade')
number = input('Dgite seu número')
print('seguem os dados:')
print(name, ' - ', city, ' - ',gender)